# Site settings
title: Trini Hot Mouth
email: sav@trinihotmouth.com
description: > # this means to ignore newlines until "baseurl:"
  Trini Hot Mouth was launched by hot sauce aficionado, Soraya Ali-van Beekum.
  A Trinidad export to Berlin, Soraya missed her native land's wide variety and
  exquisite quality of hot sauces. After sampling Berlin's hot sauces and still
  missing that Caribbean heat, Soraya began growing her own selection of peppers
  and experimenting until she found that special heat.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://trinihotmouth.com"
twitter_username: Sweetraya75

# Build settings
markdown: kramdown
